import { GoogleGenAI } from "@google/genai";
import { storage } from "../../firebase";
import { ref, uploadString, getDownloadURL } from "firebase/storage";

export async function runGenerateImageWorker(prompt: string, size: "1K" | "2K" | "4K", userId: string): Promise<string> {
  try {
    // Check for user API key for paid model
    // @ts-ignore
    if (window.aistudio && !(await window.aistudio.hasSelectedApiKey())) {
      throw new Error("API_KEY_REQUIRED");
    }
    
    // Create a new instance to ensure it picks up the latest key from the dialog
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "" });
    
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: { parts: [{ text: prompt }] },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: size
        }
      }
    });
    
    let base64Data = "";
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        base64Data = part.inlineData.data;
        break;
      }
    }
    
    if (!base64Data) {
      throw new Error("No image was generated by the model.");
    }
    
    try {
      // Attempt to upload to Firebase Storage
      const imageRef = ref(storage, `artifacts/${userId}/${Date.now()}.png`);
      await uploadString(imageRef, `data:image/png;base64,${base64Data}`, 'data_url');
      const downloadUrl = await getDownloadURL(imageRef);
      return `Successfully generated image. URL: ${downloadUrl}`;
    } catch (storageError) {
      console.warn("Failed to upload to Firebase Storage, returning base64 inline.", storageError);
      // Fallback to returning the data URL directly if storage rules block it
      return `Successfully generated image. URL: data:image/png;base64,${base64Data}`;
    }
    
  } catch (error: any) {
    console.error("Image Generation Worker Error:", error);
    if (error.message === "API_KEY_REQUIRED") {
      return "Error: The user needs to select their Gemini API Key to generate images. Please ask them to click the 'Select API Key' button in the sidebar.";
    }
    return `Image Generation Worker failed: ${error.message}`;
  }
}
