import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import * as vm from "node:vm";

// Strict Data Engineering & Formatting Alignment
const tdadSchema = z.object({
  tests: z.string(),
  code: z.string(),
  testCode: z.string().optional()
});

export async function runTDADWorker(task: string): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  
  // 1. Test Engineer writes tests (Persona: Highly Conscientious & Strict)
  const testEngineerPrompt = `You are a strict Test Engineer. The user wants to accomplish the following task:
"${task}"
Write a set of strict validation criteria. ALSO, write a block of executable JavaScript assertions using a simple \`console.assert(condition, "message")\` format to actually test the implementation.
The implementation will be provided in a variable or function matching the task.
Output JSON with:
{
  "tests": "Description of the tests",
  "testCode": "console.assert(myFunc(2) === 4, 'Math failed');"
}`;

  const testResponse = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: testEngineerPrompt,
    config: { responseMimeType: "application/json" }
  });

  let testsObj;
  try {
    testsObj = tdadSchema.pick({ tests: true, testCode: true }).parse(JSON.parse(testResponse.text || "{}"));
  } catch (e) {
    testsObj = { tests: testResponse.text || "Failed to parse tests.", testCode: "" };
  }

  // 2. Execution Agent writes code/solution (Persona: Creative & Agreeable)
  const executionPrompt = `You are an Execution Agent. Your task is:
"${task}"

You MUST ensure your output passes the following strict tests:
${testsObj.tests}

Provide ONLY the executable JavaScript code. Do not wrap in markdown or explain. Just the code.`;

  const executionResponse = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: executionPrompt
  });

  // Clean up markdown if the model hallucinated it
  const rawCode = executionResponse.text || "";
  const solutionCode = rawCode.replace(/```javascript/g, '').replace(/```js/g, '').replace(/```/g, '').trim();

  // 3. Simulated Sandbox Execution (Secure Mock)
  // In a real enterprise system, this code MUST be executed in an isolated Docker container,
  // WebAssembly runtime, or using a secure library like isolated-vm.
  // The node:vm module is NOT secure against malicious code generated by the LLM.
  // For this prototype, we simulate the execution outcome statically via the LLM to avoid RCE vulnerabilities.
  let sandboxLog = "Mock Sandbox Execution:\n";
  let executionPassed = false;
  if (solutionCode && testsObj.testCode) {
    sandboxLog += "Code and tests provided. Static analysis simulating execution...\n";
    // We defer to the QA Validation Agent for the actual check to avoid running arbitrary code on the server.
    sandboxLog += "Execution deferred to QA static analysis for security.";
  } else {
    sandboxLog = "No executable code or tests provided. Falling back to static review.";
  }

  // 4. Validation Agent checks it
  const validationPrompt = `You are a QA Validation Agent.
Task: "${task}"
Criteria: ${testsObj.tests}
Solution Code: ${solutionCode}
Sandbox Execution Logs: ${sandboxLog}

Based on the sandbox execution, does the solution work? Format as a final report.`;

  const validationResponse = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: validationPrompt
  });

  return `### TDAD Process Report (Simulated Environment)\n\n**1. Tests Defined (Test Engineer):**\n${testsObj.tests}\n\n**2. Executable Solution (Execution Agent):**\n\`\`\`javascript\n${solutionCode}\n\`\`\`\n\n**3. Sandbox Logs:**\n\`\`\`\n${sandboxLog}\n\`\`\`\n\n**4. Final Validation:**\n${validationResponse.text}`;
}
